game-paths:
    - name: 国服
      path: C:/Program Files/Wuthering Waves/Wuthering Waves Game
      has-multiple-server: true
      
genshin-path: "C:/Program Files/Genshin Impact/Genshin Impact Game/YuanShen.exe"
last-selected-path: 0
exe-name: "Wuthering Waves.exe"
link-servers:
    bilibili服: KrPcSdk_Mainland_bilibili
    官服: KrPcSdk_Mainland_official
    weGame: KrPcSdk_Mainland_wegame

link-src-path: Client/Binaries/Win64/ThirdParty/KrPcSdk_Mainland

third-tools: []